version: '3'
services:
    mongo:
        image: mongo
        ports:
            - '27017:27017'
    api:
        build: .
        ports:
          - "3000:3000"
        depends_on:
          - mongo
        volumes:
          - ./:/usr/src/app
          - /usr/src/app/node_modules
